# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-ast
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
        -   id: autopep8

-   repo: local
    hooks:
    -   id: unittest
        name: unittest
        entry: 'scripts/test.sh'
        language: system
        'types': [python]
        pass_filenames: false
        stages: [commit]
