@startuml
'autoactivate on
actor User as User
participant Obfuscator
participant DefinitionStorage
participant ChainBuilder

' comment
/'
multi line comment
'/
User -> Obfuscator : Obfuscate Request

@enduml
